### ISSUE TITLE
从零开始搭建ts+vue3组件库 （五）

### ISSUE THREAD

**Issue by SoldierAb** [SoldierAb/k-view-next#5]
# CI/CD
本文我们采用circle-ci 来做文档站点部署和npm包发布
### 写入circleci 权限
本文我们需要授权 CircleCI 自动更新 gh-pages 分支的权限，我们需要配置ssh密钥来支持
#### 生成ssh密钥
```bash
ssh-keygen -t rsa -b 4096 -C "your_email@example.com"
```
按照命令行交互，您将获得两个 ssh 密钥文件id_rsa和id_rsa.pub（记得更改默认文件位置或您的本地ssh密钥将被覆盖）

#### 上传密钥

- 通过https://github.com/<your_name>/<your_repo>/settings/Deploy keys上传您的GitHub repo设置上的id_rsa.pub。

![image.png](https://cdn.nlark.com/yuque/0/2022/png/1013483/1653621775683-30e17ee8-a36f-4cdb-9110-f95ebbb6d577.png#clientId=u53ea5c7f-6c11-4&crop=0&crop=0&crop=1&crop=1&from=paste&height=472&id=u3ad81ae5&margin=%5Bobject%20Object%5D&name=image.png&originHeight=849&originWidth=1948&originalType=binary&ratio=1&rotation=0&showTitle=false&size=116146&status=done&style=none&taskId=u14b1ad53-aac9-465c-b4e8-b9d3d9847c7&title=&width=1082.2222508913212)

- 跳转到 https://app.circleci.com/settings/project/github/<your-name>/<your-respo>/ssh?return-to=https://app.circleci.com/pipelines/github/<your-name>/<your-respo> 并添加您刚刚创建的私钥id_rsa。在主机名字段中输入github.com，然后按 提交按钮。并添加您刚刚创建的 **私钥id_rsa**。 在主机名字段 **hostname **中输 入 github.com, 然后按提交按钮

![image.png](https://cdn.nlark.com/yuque/0/2022/png/1013483/1653621998816-4673c9d9-79c0-4719-aef3-961e2010d74f.png#clientId=u53ea5c7f-6c11-4&crop=0&crop=0&crop=1&crop=1&from=paste&height=746&id=ub111fbda&margin=%5Bobject%20Object%5D&name=image.png&originHeight=1342&originWidth=2089&originalType=binary&ratio=1&rotation=0&showTitle=false&size=306230&status=done&style=none&taskId=u5b7041c9-fe9a-499a-979d-f1af4eff51f&title=&width=1160.5555862997794)

#### 保存 fingerprints 
后面yml文件配置中会用到
```bash
 - add_ssh_keys:
          fingerprints:
            - "ae:xxxxxxxxx:c3:4f:0f:ff:5f"
```

#### npm-auth-token 获取

- 查看npm 配置
```bash
npm config ls -l
```
![image.png](https://cdn.nlark.com/yuque/0/2022/png/1013483/1653622670131-6e90267f-8c68-4e7b-b56d-8b9cf2217674.png#clientId=u53ea5c7f-6c11-4&crop=0&crop=0&crop=1&crop=1&from=paste&height=461&id=u04a9c38f&margin=%5Bobject%20Object%5D&name=image.png&originHeight=830&originWidth=2476&originalType=binary&ratio=1&rotation=0&showTitle=false&size=826547&status=done&style=none&taskId=ua1e9c91b-3c64-46eb-9fe3-de53a383459&title=&width=1375.5555919953345)
```bash
cat /Users/gorgechan/.npmrc
```
![image.png](https://cdn.nlark.com/yuque/0/2022/png/1013483/1653622932021-bae81e7c-0eff-416a-bbd0-9afb5764f58d.png#clientId=u53ea5c7f-6c11-4&crop=0&crop=0&crop=1&crop=1&from=paste&height=400&id=ub607bbca&margin=%5Bobject%20Object%5D&name=image.png&originHeight=720&originWidth=2428&originalType=binary&ratio=1&rotation=0&showTitle=false&size=671021&status=done&style=none&taskId=u70ec4371-5cc9-4461-8f55-5fb506aabe0&title=&width=1348.8889246222423)
> 找到你要发布的npm源的autoToken， 复制 **_“=” 后的字符串，供下一步配置使用_**

#### circle-ci 环境变量配置
![image.png](https://cdn.nlark.com/yuque/0/2022/png/1013483/1653622402366-9cab8cda-8b61-4282-b3e5-ab36bd3f9fc1.png#clientId=u53ea5c7f-6c11-4&crop=0&crop=0&crop=1&crop=1&from=paste&height=564&id=u041c3985&margin=%5Bobject%20Object%5D&name=image.png&originHeight=1015&originWidth=2186&originalType=binary&ratio=1&rotation=0&showTitle=false&size=167037&status=done&style=none&taskId=u0cf42842-8c77-49b2-b7f1-22d0b0c074c&title=&width=1214.4444766162362)<br />至此，我们的环境变量配置完成啦 🎸

### 配置文件主要由3部分组成：

- 版本 version
   - 你要使用的circleci 版本
- 工作 jobs
   - 需要执行的job， 名称需要唯一
   - 如果不使用工作流workflows，则必须包含 build 的 job 来作为默认工作
- 工作流
   - 用于编排所有的 job

### 工作
我们需要明确我们需要做的事情：

- 依赖安装
- 文档站点部署
- npm包发布
### 内容
```yaml
version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
      - image: circleci/node:14

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
         keys:
         - v1-dependencies-{{ checksum "package.json" }}
         # fallback to using the latest cache if no exact match is found
         - v1-dependencies-
      - run:
          name: Install
          command: yarn install
      - save_cache:
         paths:
           - node_modules
         key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/repo
          paths: .
  site:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - add_ssh_keys:
          fingerprints:
            - "ae:9d:1b:7b:6a:98:6b:1e:46:77:49:c3:4f:0f:ff:5f"
      - run:
          name: Knows_hosts add
          command: ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run:
          name: Prepare shell commands
          command: cp .circleci/github.sh ./ && chmod +x ./github.sh && ls -a
      - run:
          name: Run github shell
          command: ./github.sh
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Run tests
          command: yarn test
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate in registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish Package
          command: npm publish


# Orchestrate our job run sequence
workflows:
  version: 2
  build-deploy:
    jobs:
      - install:
          filters: &tagged
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - site:
          requires:
            - install
          filters:
            <<: *tagged
      - test:
          requires:
            - install
          filters:
            <<: *tagged
      - deploy:
          requires:
            - test
          filters:
            <<: *tagged
```

## .circleci/github.sh
```bash
#!/usr/bin/env sh

# 构建
yarn docs:build
# 进入生成的构建文件夹
cd dist
git init

git config user.email "ab140140@163.com"
git config user.name "SoldierAb"
git checkout -b gh-pages
git add .
git commit -m 'docs: site deploy'

echo "before docs deploy"

git push --force git@github.com:SoldierAb/k-view-next.git gh-pages


```

### 状态查看
通过github actions 和circle-ci的项目管理面板，我们就能看到我们的持续集成状态啦 🚀  <br />![image.png](https://cdn.nlark.com/yuque/0/2022/png/1013483/1653623227115-aad05220-08e2-4af6-aa67-ffae6f43d393.png#clientId=u53ea5c7f-6c11-4&crop=0&crop=0&crop=1&crop=1&from=paste&height=524&id=ubb3737d7&margin=%5Bobject%20Object%5D&name=image.png&originHeight=943&originWidth=2098&originalType=binary&ratio=1&rotation=0&showTitle=false&size=206632&status=done&style=none&taskId=ud76ad1d7-6b69-40a5-84a2-724322bc4ae&title=&width=1165.5555864322341)<br />![image.png](https://cdn.nlark.com/yuque/0/2022/png/1013483/1653623355552-327de060-1ce1-4e50-8d7d-fd98b6a293b3.png#clientId=u53ea5c7f-6c11-4&crop=0&crop=0&crop=1&crop=1&from=paste&height=290&id=uc3642c10&margin=%5Bobject%20Object%5D&name=image.png&originHeight=522&originWidth=2086&originalType=binary&ratio=1&rotation=0&showTitle=false&size=138303&status=done&style=none&taskId=u11918acb-17f5-4d62-a0e8-ca49e59bfc1&title=&width=1158.888919588961)

### gh-pages 查看
[https://soldierab.github.io/k-view-next/](https://soldierab.github.io/k-view-next/)<br />![image.png](https://cdn.nlark.com/yuque/0/2022/png/1013483/1653623492760-18697cd1-7bc3-4027-949e-9ba4ee03e88a.png#clientId=u53ea5c7f-6c11-4&crop=0&crop=0&crop=1&crop=1&from=paste&height=749&id=u806c16d3&margin=%5Bobject%20Object%5D&name=image.png&originHeight=1349&originWidth=2523&originalType=binary&ratio=1&rotation=0&showTitle=false&size=136085&status=done&style=none&taskId=u9a24ee10-f5c8-4126-9298-976418e0733&title=&width=1401.6667037981538)
### npm包查看
[https://www.npmjs.com/package/k-view-next](https://www.npmjs.com/package/k-view-next)<br />![image.png](https://cdn.nlark.com/yuque/0/2022/png/1013483/1653623565227-39e62fa0-5c1c-4e2d-98fe-2448586b9807.png#clientId=u53ea5c7f-6c11-4&crop=0&crop=0&crop=1&crop=1&from=paste&height=666&id=u6e10f0ae&margin=%5Bobject%20Object%5D&name=image.png&originHeight=1198&originWidth=1475&originalType=binary&ratio=1&rotation=0&showTitle=false&size=207195&status=done&style=none&taskId=u0a6b8e9c-b6e9-49ff-8b00-3d995f30d46&title=&width=819.4444661523095)

# 总结
一个组件库从需求、设计、开发、部门内方案实施，这一系列的流程走下来，相信我们能一起成长的！ 🚀
